[workspace]
members = [
    "rust/library",
    "rust/test_executor",
    "problems/problems_1",
    "problems/problems_2",
	"problems/problems_2766",
    "problems/problems_279",
	"problems/problems_2844",
	"problems/problems_49",
	"problems/problems_2740",
	"problems/problems_239",
	"problems/problems_3106",
	"problems/problems_34",
	"problems/problems_102",
    "problems/problems_1379",
    "problems/problems_236",
	"problems/problems_116",
	"problems/problems_117",
	"problems/problems_133",
	"problems/problems_138",
	"problems/problems_699",
	"problems/problems_39",
	"problems/problems_215",
	"problems/problems_682",
	"problems/problems_56",
	"problems/problems_2961",
	"problems/problems_394",
	"problems/problems_3111",
	"problems/problems_5",
	"problems/problems_LCP_40",
	"problems/problems_169",
]

[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
authors = ["benhao"]
description = "LeetCode solutions in Rust"
readme = "README.md"

[[test]]
name = "solution_test"
path = "rust/test_executor/tests/test.rs"

[[test]]
name = "solutions_test"
path = "rust/test_executor/tests/solutions_test.rs"

[dependencies]
serde_json = "1.0"
rand = "0.8.4"
regex = "1.10.5"
assert_float_eq = "1"
test_executor = { path = "rust/test_executor", features = ["run_test"] }
solution_1 = { path = "problems/problems_1", features = ["solution_1"] }
solution_2 = { path = "problems/problems_2", features = ["solution_2"] }
solution_2766 = { path = "problems/problems_2766", features = ["solution_2766"] }
solution_279 = { path = "problems/problems_279", features = ["solution_279"] }
solution_2844 = { path = "problems/problems_2844", features = ["solution_2844"] }
solution_49 = { path = "problems/problems_49", features = ["solution_49"] }
solution_2740 = { path = "problems/problems_2740", features = ["solution_2740"] }
solution_239 = { path = "problems/problems_239", features = ["solution_239"] }
solution_3106 = { path = "problems/problems_3106", features = ["solution_3106"] }
solution_34 = { path = "problems/problems_34", features = ["solution_34"] }
solution_102 = { path = "problems/problems_102", features = ["solution_102"] }
solution_1379 = { path = "problems/problems_1379", features = ["solution_1379"] }
solution_236 = { path = "problems/problems_236", features = ["solution_236"] }
solution_116 = { path = "problems/problems_116", features = ["solution_116"] }
solution_117 = { path = "problems/problems_117", features = ["solution_117"] }
solution_133 = { path = "problems/problems_133", features = ["solution_133"] }
solution_138 = { path = "problems/problems_138", features = ["solution_138"] }
solution_699 = { path = "problems/problems_699", features = ["solution_699"] }
solution_39 = { path = "problems/problems_39", features = ["solution_39"] }
solution_215 = { path = "problems/problems_215", features = ["solution_215"] }
solution_682 = { path = "problems/problems_682", features = ["solution_682"] }
solution_56 = { path = "problems/problems_56", features = ["solution_56"] }
solution_2961 = { path = "problems/problems_2961", features = ["solution_2961"] }
solution_394 = { path = "problems/problems_394", features = ["solution_394"] }
solution_3111 = { path = "problems/problems_3111", features = ["solution_3111"] }
solution_5 = { path = "problems/problems_5", features = ["solution_5"] }
solution_LCP_40 = { path = "problems/problems_LCP_40", features = ["solution_LCP_40"] }
solution_169 = { path = "problems/problems_169", features = ["solution_169"] }
