[workspace]
members = [
    "rust/library",
    "rust/test_executor",
    "problems/problems_1",
    "problems/problems_2",
	"problems/problems_2766",
    "problems/problems_279",
	"problems/problems_2844",
	"problems/problems_49",
]

[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
authors = ["benhao"]
description = "LeetCode solutions in Rust"
readme = "README.md"

[[test]]
name = "solution_test"
path = "rust/test_executor/tests/test.rs"

[[test]]
name = "solutions_test"
path = "rust/test_executor/tests/solutions_test.rs"

[dependencies]
serde_json = "1.0"
rand = "0.8.4"
regex = "1.10.5"
assert_float_eq = "1"
test_executor = { path = "rust/test_executor", features = ["run_test"] }
solution_1 = { path = "problems/problems_1", features = ["solution_1"] }
solution_2 = { path = "problems/problems_2", features = ["solution_2"] }
solution_2766 = { path = "problems/problems_2766", features = ["solution_2766"] }
solution_279 = { path = "problems/problems_279", features = ["solution_279"] }
solution_2844 = { path = "problems/problems_2844", features = ["solution_2844"] }
solution_49 = { path = "problems/problems_49", features = ["solution_49"] }
