[tool.semantic_release]
# 或者使用单独的文件
version_variable = "3.14"
commit_version_number = true
upload_to_pypi = false
upload_to_release = true
patch_without_tag = true
major_on_zero = true
commit_parser = "angular"
version_source = "commit"
changelog_file = "CHANGELOG.md"

[tool.semantic_release.changelog]
template = "keepachangelog"
exclude_commit_patterns = [
    "^skip",
    "^chore",
    "^docs",
    "^test",
    "^style",
    "^refactor",
]